#!/usr/bin/env python3
"""
Café Athena — Reorder Mise en Place / Ingredients

Flips the order of the Mise en Place and Ingredients sections so that
Ingredients comes first (procure, then prep). Operates on The Manual
source files only — site content is regenerated by prepare-content.py.

Safe by default: prints a dry-run report and writes nothing unless
--apply is passed.

Usage:
    python3 scripts/reorder_mise_ingredients.py            # dry run
    python3 scripts/reorder_mise_ingredients.py --apply     # write changes
    python3 scripts/reorder_mise_ingredients.py --chapter 9
    python3 scripts/reorder_mise_ingredients.py --file "The Manual/.../09-05 ....md"
"""

import argparse
import glob
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RECIPES_JSON = os.path.join(BASE, "recipes.json")
MANUAL = os.path.join(BASE, "The Manual")

MISE_RE = re.compile(r"^## +Mise", re.IGNORECASE)
ING_RE = re.compile(r"^## +Ingredient", re.IGNORECASE)
HEADER_RE = re.compile(r"^## +")


def header_indices(lines):
    """Return list of (line_index, line_text) for every '## ' header."""
    return [(i, ln) for i, ln in enumerate(lines) if HEADER_RE.match(ln)]


def flip_once(lines):
    """Flip a single Mise→Ingredients adjacent pair that is in the wrong
    order (Mise before Ingredients). Returns new lines, or None if no
    such pattern exists.

    A section block runs from its '## ' header up to the line before the
    next '## ' header (carrying its own trailing '---' separator), so two
    adjacent blocks can be transposed by a clean range swap.
    """
    headers = header_indices(lines)
    for pos, (idx, text) in enumerate(headers):
        if not MISE_RE.match(text):
            continue
        # The header immediately following Mise must be Ingredients.
        if pos + 1 >= len(headers):
            return None
        next_idx, next_text = headers[pos + 1]
        if not ING_RE.match(next_text):
            continue  # not the pattern we flip; keep scanning

        mise_start = idx
        ing_start = next_idx
        # End of the Ingredients block = start of the header after it,
        # or end of file if Ingredients is the last section.
        ing_end = headers[pos + 2][0] if pos + 2 < len(headers) else len(lines)

        mise_block = lines[mise_start:ing_start]
        ing_block = lines[ing_start:ing_end]
        new_lines = (
            lines[:mise_start] + ing_block + mise_block + lines[ing_end:]
        )
        return new_lines
    return None


def reorder(text):
    """Return (new_text, status). Status is one of:
    swapped, already-correct, skip-missing, error-content-loss.
    """
    if text.startswith("---"):
        parts = text.split("---", 2)
        front, body = "---" + parts[1] + "---", parts[2]
    else:
        front, body = "", text

    lines = body.split("\n")

    has_mise = any(MISE_RE.match(l) for l in lines)
    has_ing = any(ING_RE.match(l) for l in lines)
    if not (has_mise and has_ing):
        return text, "skip-missing"

    before_sig = sorted(l.strip() for l in lines if l.strip())

    changed = False
    while True:
        flipped = flip_once(lines)
        if flipped is None:
            break
        lines = flipped
        changed = True

    if not changed:
        return text, "already-correct"

    after_sig = sorted(l.strip() for l in lines if l.strip())
    if before_sig != after_sig:
        return text, "error-content-loss"

    return front + "\n".join(lines), "swapped"


def recipe_files(args):
    """Yield (recipe_id, filepath) for files to process."""
    if args.file:
        path = args.file if os.path.isabs(args.file) else os.path.join(BASE, args.file)
        yield ("(file)", path)
        return

    with open(RECIPES_JSON, encoding="utf-8") as f:
        data = json.load(f)

    for r in data["recipes"]:
        if r.get("type") == "technique":
            continue
        rid = r["id"]
        if args.chapter is not None and r.get("chapter") != args.chapter:
            continue
        hits = glob.glob(os.path.join(MANUAL, "**", f"{rid} *.md"), recursive=True)
        if not hits:
            print(f"  WARN  {rid}: no Manual file found")
            continue
        yield (rid, hits[0])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="write changes (default: dry run)")
    ap.add_argument("--chapter", type=int, help="restrict to one chapter")
    ap.add_argument("--file", help="process a single file")
    args = ap.parse_args()

    counts = {"swapped": 0, "already-correct": 0, "skip-missing": 0, "error-content-loss": 0}
    errors = []

    for rid, path in recipe_files(args):
        with open(path, encoding="utf-8") as f:
            original = f.read()
        new_text, status = reorder(original)
        counts[status] = counts.get(status, 0) + 1
        name = os.path.basename(path)

        if status == "swapped":
            print(f"  SWAP  {rid}  {name}")
            if args.apply:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(new_text)
        elif status == "skip-missing":
            print(f"  SKIP  {rid}  {name}  (no Mise and/or Ingredients — review)")
        elif status == "error-content-loss":
            print(f"  ERROR {rid}  {name}  (content mismatch — NOT written)")
            errors.append(rid)
        # already-correct: silent

    mode = "APPLIED" if args.apply else "DRY RUN (no files written — pass --apply to write)"
    print(f"\n{mode}")
    print(
        f"  swapped: {counts['swapped']}  |  already-correct: {counts['already-correct']}  "
        f"|  skipped (missing): {counts['skip-missing']}  |  errors: {counts['error-content-loss']}"
    )
    if errors:
        print(f"  ERRORS: {', '.join(errors)}")
        sys.exit(1)


if __name__ == "__main__":
    main()
